# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: "http://noellebrockhoff.com"
title: Noelle Brockhoff - Digital Creative
email: noelle@noellebrockhoff.com
author: Noelle Brockhoff
description: The Abbreviated Digital Portfolio of Noelle Brockhoff
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: facebook
    url: https://facebook.com/derrb
  - title: github
    url: https://github.com/noellebrockhoff
  - title: linkedin
    url: https://www.linkedin.com/in/derrb
